tasks:
  - init: |
      mvn -am -pl war,bom -P quick-build install
    command: |      
      cd war
      curl https://gist.githubusercontent.com/timja/fe73f0a0f98afe4d9356e7ce6752d95b/raw/98ad71080e91ed75824ec410ff905419e3788065/init.sh | bash
      mvn jetty:run -Dhost=0.0.0.0
    name: Run
  - command: gp await-port 8080 && gp url 8080 && gp preview $(gp url 8080)/jenkins/
    name: Preview

github:
  prebuilds:
    pullRequestsFromForks: true
    addBadge: true

jetbrains:
  intellij:
    plugins:
      - Stapler plugin for IntelliJ IDEA
    prebuilds:
      version: stable

image:
  file: .gitpod/Dockerfile
